services:
  db:
    image: "postgres:14.15-alpine"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 2

  adsync-backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    environment:
      - DB_URL=jdbc:postgresql://db:5432/db
      - DB_USERNAME=user
      - DB_PASSWORD=password
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  adsync-frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_URL: http://localhost:8080
    depends_on:
      adsync-backend:
        condition: service_started
    ports:
      - "5173:5173"

volumes:
  postgres_data: